services:
  db:
    image: mariadb
    container_name: '${PROJECT_NAME}_db'
    restart: always
    expose:
      - 3306  
    ports:
      - 3306:3306    
    volumes:
      - metabase-data:${DB_DATA_DIR}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: '${PROJECT_NAME}_pma'
    restart: always
    ports:
      - 4380:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_ROOT_PASSWORD}

  metabase:
    image: metabase/metabase:latest
    container_name: '${PROJECT_NAME}_app'
    restart: always
    environment:
      MB_DB_TYPE: "${DB_DRIVER}"
      MB_DB_DBNAME: "${DB_NAME}"
      MB_DB_PORT: "5432"
      MB_DB_USER: "${DB_USER}"
      MB_DB_PASS: "${DB_PASSWORD}"
      MB_DB_HOST: "db"
      MB_PASSWORD_COMPLEXITY: strong
      MB_PASSWORD_LENGTH: 10
      JAVA_TIMEZONE: "${MB_JAVA_TIMEZONE}"
    ports:
      - 127.0.0.1:${MB_PORT}:3000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      default:
        ipv4_address: 172.17.10.10
    depends_on:
      - db


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.17.10.0/24"

volumes:
  metabase-data:
